# Particionando dados

Separando os dados em treinamento, validação e teste. 

Esse notebook irá usar um dos lugares de gravação, chamado de `Recording_4`, como conjunto de teste e os demais serão usados para treinamento/validação.

In [1]:
from pathlib import Path

import sklearn
import pandas as pd

In [2]:
clip_labels_file = Path("clip_labels.csv")
assert clip_labels_file.exists(), "O clip_labels.csv não foi encontrado. Execute o notebook 01_visualizando.ipynb para criar esse arquivo"

In [3]:
clip_labels = pd.read_csv(clip_labels_file, index_col=["file", "start_time", "end_time"])
clip_labels.head()

                                                                        NOCA  \
file                                               start_time end_time
../data/mp3_Files/Recording_3/Recording_3_Segme... 0.0        3.0       True
                                                   3.0        6.0       True
                                                   6.0        9.0       True
                                                   9.0        12.0      True
                                                   12.0       15.0      True

                                                                        EATO  \
file                                               start_time end_time
../data/mp3_Files/Recording_3/Recording_3_Segme... 0.0        3.0       True
                                                   3.0        6.0       True
                                                   6.0        9.0       True
                                                   9.0        12.0      True
                                                   12.0       15.0      True

                                                                         SCTA  \
file                                               start_time end_time
../data/mp3_Files/Recording_3/Recording_3_Segme... 0.0        3.0       False
                                                   3.0        6.0       False
                                                   6.0        9.0       False
                                                   9.0        12.0      False
                                                   12.0       15.0      False

                                                                         BAWW  \
file                                               start_time end_time
../data/mp3_Files/Recording_3/Recording_3_Segme... 0.0        3.0       False
                                                   3.0        6.0       False
                                                   6.0        9.0       False
                                                   9.0        12.0      False
                                                   12.0       15.0      False

                                                                         BCCH  \
file                                               start_time end_time
../data/mp3_Files/Recording_3/Recording_3_Segme... 0.0        3.0       False
                                                   3.0        6.0       False
                                                   6.0        9.0       False
                                                   9.0        12.0      False
                                                   12.0       15.0      False

                                                                         AMCR  \
file                                               start_time end_time
../data/mp3_Files/Recording_3/Recording_3_Segme... 0.0        3.0       False
                                                   3.0        6.0       False
                                                   6.0        9.0       False
                                                   9.0        12.0      False
                                                   12.0       15.0      False

                                                                         NOFL
file                                               start_time end_time
../data/mp3_Files/Recording_3/Recording_3_Segme... 0.0        3.0       False
                                                   3.0        6.0       False
                                                   6.0        9.0       False
                                                   9.0        12.0      False
                                                   12.0       15.0      False

In [4]:
mask = clip_labels.reset_index()["file"].apply(lambda x: "Recording_4" in x).values
test_set = clip_labels[mask]
test_set.head()

                                                                         NOCA  \
file                                               start_time end_time
../data/mp3_Files/Recording_4/Recording_4_Segme... 0.0        3.0        True
                                                   3.0        6.0       False
                                                   6.0        9.0        True
                                                   9.0        12.0      False
                                                   12.0       15.0       True

                                                                         EATO  \
file                                               start_time end_time
../data/mp3_Files/Recording_4/Recording_4_Segme... 0.0        3.0        True
                                                   3.0        6.0        True
                                                   6.0        9.0       False
                                                   9.0        12.0       True
                                                   12.0       15.0       True

                                                                         SCTA  \
file                                               start_time end_time
../data/mp3_Files/Recording_4/Recording_4_Segme... 0.0        3.0       False
                                                   3.0        6.0       False
                                                   6.0        9.0       False
                                                   9.0        12.0      False
                                                   12.0       15.0      False

                                                                         BAWW  \
file                                               start_time end_time
../data/mp3_Files/Recording_4/Recording_4_Segme... 0.0        3.0       False
                                                   3.0        6.0       False
                                                   6.0        9.0       False
                                                   9.0        12.0      False
                                                   12.0       15.0      False

                                                                         BCCH  \
file                                               start_time end_time
../data/mp3_Files/Recording_4/Recording_4_Segme... 0.0        3.0       False
                                                   3.0        6.0       False
                                                   6.0        9.0       False
                                                   9.0        12.0      False
                                                   12.0       15.0      False

                                                                         AMCR  \
file                                               start_time end_time
../data/mp3_Files/Recording_4/Recording_4_Segme... 0.0        3.0       False
                                                   3.0        6.0       False
                                                   6.0        9.0       False
                                                   9.0        12.0      False
                                                   12.0       15.0      False

                                                                         NOFL
file                                               start_time end_time
../data/mp3_Files/Recording_4/Recording_4_Segme... 0.0        3.0       False
                                                   3.0        6.0       False
                                                   6.0        9.0       False
                                                   9.0        12.0      False
                                                   12.0       15.0      False

In [5]:
test_set.to_csv("test_set.csv")

Agora que separamos os dados de teste, os demais arquivos serão utilizados para treino e validação.

In [6]:
train_and_val_set = clip_labels.drop(test_set.index)

In [7]:
train_df, valid_df = sklearn.model_selection.train_test_split(
    train_and_val_set, test_size=0.1, random_state=0
)

In [8]:
train_df.to_csv("train.csv")

In [9]:
valid_df.to_csv("valid.csv")